paths:
  uploads: uploads
  static: ''
  collections: ''
  data: ''
  layouts:
collections_config:
posts:
    path: content/posts
    output: true
    url: /posts/{category|slugify}/[slug].html
    icon: event_available
  staff:
    path: content/staff_members
    parser: yaml
    output: false
    icon: people
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
timezone: Etc/UTC
